version: "3"
services:
  api:
    image: wycliffeassociates/irg9000
    env_file:
      - .env
    environment:
      FROM_EMAIL_ADDRESS: ${FROM_EMAIL_ADDRESS}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      TO_EMAIL_ADDRESS: ${TO_EMAIL_ADDRESS}
      SMTP_HOST: ${SMTP_HOST}
    volumes:
      - docker_pdf_output:/output
    entrypoint:
      # Configure the server for fastapi, i.e., uvicorn
      - uvicorn
      - --host=0.0.0.0
      - --port=80
      - --reload
      - document.entrypoints.app:app
    ports:
      - "5005:80"
  web:
    build: ./web
    ports:
      - "8089:80"
    volumes:
      - docker_pdf_output:/srv/content

volumes:
  docker_pdf_output:
